"""empty message

Revision ID: 2efb563474ee
Revises: 491895a16de3
Create Date: 2021-03-17 19:54:34.183359

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2efb563474ee'
down_revision = '491895a16de3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_many_relation_table')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', mysql.VARCHAR(length=64), nullable=True))
    op.create_table('battery_many_relation_table',
    sa.Column('device_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('battery_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['battery_id'], ['battery_logger.id'], name='battery_many_relation_table_ibfk_1'),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], name='battery_many_relation_table_ibfk_2'),
    sa.PrimaryKeyConstraint('device_id', 'battery_id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
