"""empty message

Revision ID: 4a9950db4e7d
Revises: 2efb563474ee
Create Date: 2021-03-17 19:55:43.868228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a9950db4e7d'
down_revision = '2efb563474ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('battery_logger', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'battery_logger', 'device', ['device_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'battery_logger', type_='foreignkey')
    op.drop_column('battery_logger', 'device_id')
    # ### end Alembic commands ###
