"""empty message

Revision ID: 5fa1659f898f
Revises: 82d846b9b867
Create Date: 2021-03-18 18:28:33.578094

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5fa1659f898f'
down_revision = '82d846b9b867'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'tokens')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tokens', mysql.TEXT(), nullable=True))
    # ### end Alembic commands ###
