"""empty message

Revision ID: 66041588c137
Revises: 
Create Date: 2021-02-12 19:17:27.311179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66041588c137'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battery_logger',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('timestamp_time', sa.TIMESTAMP(), nullable=False),
    sa.Column('device_battery', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battery_logger')
    # ### end Alembic commands ###
