"""empty message

Revision ID: 6d292d3173b6
Revises: 811069aa74f0
Create Date: 2021-01-08 16:00:45.840657

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6d292d3173b6'
down_revision = '811069aa74f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('device', 'timestamp',
               existing_type=mysql.DATETIME(),
               nullable=False)
    # ### end Alembic commands ###
