"""empty message

Revision ID: 82d846b9b867
Revises: 4a9950db4e7d
Create Date: 2021-03-18 18:19:07.204611

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '82d846b9b867'
down_revision = '4a9950db4e7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('battery_logger', 'device_battery',
               existing_type=mysql.FLOAT(),
               nullable=False)
    op.alter_column('battery_logger', 'device_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.drop_constraint('battery_logger_ibfk_1', 'battery_logger', type_='foreignkey')
    op.create_foreign_key(None, 'battery_logger', 'device', ['device_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'battery_logger', type_='foreignkey')
    op.create_foreign_key('battery_logger_ibfk_1', 'battery_logger', 'device', ['device_id'], ['id'])
    op.alter_column('battery_logger', 'device_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('battery_logger', 'device_battery',
               existing_type=mysql.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
