"""empty message

Revision ID: f054b6420d7d
Revises: 5fa1659f898f
Create Date: 2021-03-18 18:42:18.545485

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f054b6420d7d'
down_revision = '5fa1659f898f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=512),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'password',
               existing_type=mysql.VARCHAR(length=512),
               nullable=True)
    # ### end Alembic commands ###
