"""empty message

Revision ID: fc77ab89e5d9
Revises: 
Create Date: 2021-01-04 18:26:13.538132

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fc77ab89e5d9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('message_queue')
    op.drop_table('appliance')
    op.drop_table('permission__user__appliance')
    op.drop_table('permission')
    op.drop_table('user')
    op.drop_table('scout')
    op.drop_table('permission__user__scout')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permission__user__scout',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('scout_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='permission__user__scout_ibfk_3'),
    sa.ForeignKeyConstraint(['scout_id'], ['scout.id'], name='permission__user__scout_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='permission__user__scout_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('scout',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('appliance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('battery_power', mysql.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.id'], name='scout_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('password_hash', mysql.VARCHAR(length=512), nullable=True),
    sa.Column('first_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('last_name', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('phone_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('email', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('permission',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('permission__user__appliance',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('appliance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('permission_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.id'], name='permission__user__appliance_ibfk_2'),
    sa.ForeignKeyConstraint(['permission_id'], ['permission.id'], name='permission__user__appliance_ibfk_3'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='permission__user__appliance_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('appliance',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('type', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('status', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('alert_message', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('alert_time', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('alert_email', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('alert_text', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.CheckConstraint('`alert_email` in (0,1)', name='CONSTRAINT_2'),
    sa.CheckConstraint('`alert_text` in (0,1)', name='CONSTRAINT_3'),
    sa.CheckConstraint('`status` in (0,1)', name='CONSTRAINT_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('message_queue',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('appliance_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('time', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appliance_id'], ['appliance.id'], name='message_queue_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
